# # configs/model/fuser.yaml
# 融合模型参数
# @package model

fuser_params:
  type: 'elastic_net'             # 元模型类型: 'elastic_net' (推荐), 'ridge' (线性，稳健) 或 'mlp' (非线性，更复杂). 
  alpha: 0.0001                # 如果使用 Ridge，此为正则化强度. 值越大，正则化越强，模型越简单. 
  l1_ratio: 0.5            # (仅 ElasticNet) L1 正则化的比例 (0=Ridge, 1=Lasso)。0.5 是一个很好的平衡点。
  stability_threshold: 0.5  # IC 稳定性分数的阈值（变异系数）. 交叉验证的 IC 标准差/均值 > 此值，则认为模型不稳定并回退. 
  pred_clip: 0.05           # 预测结果限幅. 使用 tanh 将最终输出限制在 ±5% 以内，防止极端信号. 
  smooth_window: 3          # 实盘防抖动平滑窗口. 对最近 N 次的预测取平均，使信号输出更平滑. 设为 1 则不平滑. 
  verbose: True             # 是否打印融合模型在训练和预测时的详细日志. 